### ISSUE TITLE
Add spec suite

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/Parsistence#4]
\o/

**Comment by DiogoAndre** [comment]
Hi @jamonholmgren!  Nice to Persistence coming back to live. I'm exploring Parse a little bit and can dedicate some effort to this. 

To write proper tests we would have to add the Parse SDK to this gem right? Via Cocapods or directly. That's not a big issue, I guess. But how would we test without providing a Parse app id and client key? is it even possible?

Cheers!

**Comment by jamonholmgren** [comment]
Awesome, @DiogoAndre ! I really like Parse, still, so I'm definitely interested in continuing to improve Parsistence.

We can just use the CocoaPod, which is what I've done in my apps. Include `motion-cocoapods` and then in the config block in https://github.com/infinitered/Parsistence/blob/master/lib/Parsistence.rb:

```ruby
app.pods do
  pod 'Parse', '~> 1.6'
end
```

**Comment by jamonholmgren** [comment]
Regarding the API key, I think we should use environment variables that we can set either while running the specs or in the .zshrc or similar file. Travis has the ability to do env vars, so we'll use that.

For local specs:

```sh-session
$ PARSE_APPLICATION_ID=appidhere PARSE_CLIENT_KEY=clientkeyhere bundle exec rake spec
```

**Comment by jamonholmgren** [comment]
![2015-09-15-poema](https://cloud.githubusercontent.com/assets/1479215/9883152/4ff55162-5b8d-11e5-90d6-c656556ab2d4.png)

**Comment by DiogoAndre** [comment]
Awesome! Will try my hand at it
